import "../../styles/dashboard.css";

export default function Signup() {

  return (
    <div
      className="dashboard-container"
      style={{
        minHeight: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background:
          "linear-gradient(135deg, #0f172a 0%, #1e3a8a 45%, #2563eb 100%)",
        padding: "30px",
        overflow: "hidden",
        position: "relative",
      }}
    >

      {/* BACKGROUND GLOW */}
      <div
        style={{
          position: "absolute",
          width: "420px",
          height: "420px",
          borderRadius: "50%",
          background:
            "rgba(255,255,255,0.08)",
          top: "-120px",
          right: "-120px",
          filter: "blur(10px)",
        }}
      />

      <div
        style={{
          position: "absolute",
          width: "300px",
          height: "300px",
          borderRadius: "50%",
          background:
            "rgba(37,99,235,0.25)",
          bottom: "-100px",
          left: "-100px",
          filter: "blur(18px)",
        }}
      />

      {/* MAIN CARD */}
      <div
        className="form-card"
        style={{
          width: "100%",
          maxWidth: "620px",
          background:
            "rgba(255,255,255,0.96)",
          backdropFilter: "blur(18px)",
          borderRadius: "30px",
          padding: "48px",
          textAlign: "center",
          boxShadow:
            "0 25px 70px rgba(0,0,0,0.28)",
          position: "relative",
          zIndex: 2,
        }}
      >

        {/* ICON */}
        <div
          style={{
            fontSize: "72px",
            marginBottom: "18px",
          }}
        >
          🎓
        </div>

        {/* TITLE */}
        <h1
          style={{
            fontSize: "38px",
            fontWeight: "800",
            color: "#0f172a",
            marginBottom: "16px",
            letterSpacing: "-0.8px",
          }}
        >
          Student Registration Disabled
        </h1>

        {/* SUBTEXT */}
        <p
          style={{
            color: "#475569",
            fontSize: "17px",
            lineHeight: "1.9",
            marginBottom: "34px",
            maxWidth: "480px",
            marginInline: "auto",
          }}
        >
          Student accounts are officially created
          and managed by the Head of Department
          (HOD) through the university academic
          administration system.
        </p>

        {/* INFO BOX */}
        <div
          style={{
            background:
              "linear-gradient(135deg, #dbeafe, #eff6ff)",
            border:
              "1px solid #bfdbfe",
            borderRadius: "22px",
            padding: "26px",
            marginBottom: "30px",
            textAlign: "left",
          }}
        >

          <h3
            style={{
              color: "#1d4ed8",
              marginBottom: "16px",
              fontSize: "22px",
              fontWeight: "700",
            }}
          >
            📌 Important Information
          </h3>

          <ul
            style={{
              color: "#334155",
              lineHeight: "2",
              paddingLeft: "20px",
              fontSize: "15px",
            }}
          >

            <li>
              Login credentials are generated by the department.
            </li>

            <li>
              Your assigned mentor details will automatically appear after activation.
            </li>

            <li>
              Semester tracking and mentor communication features are enabled after account approval.
            </li>

            <li>
              Please regularly check your university email inbox.
            </li>

          </ul>

        </div>

        {/* CONTACT CARD */}
        <div
          style={{
            background:
              "#f8fafc",
            borderRadius: "18px",
            padding: "20px",
            border:
              "1px solid #e2e8f0",
          }}
        >

          <div
            style={{
              fontSize: "15px",
              color: "#475569",
              lineHeight: "1.8",
            }}
          >
            <strong
              style={{
                color: "#0f172a",
              }}
            >
              Need help?
            </strong>

            <br />

            Contact your department office or HOD
            if your login credentials have not been received.
          </div>

        </div>

      </div>

    </div>
  );
}